// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emkodddgridhgnlpffaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVta29kZGRncmlkaGdubHBmZmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTIyOTksImV4cCI6MjA2MDY2ODI5OX0.r5e9t1_SrGtQwnXHfgBqwzYh53t4bv6itHnbBSeSL1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);